name: Lint

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  # Replace pull_request with pull_request_target if you
  # plan to use this action with forks, see the Limitations section
  pull_request:
    branches:
      - main
jobs:
  run-linters:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bun: ["1.1.42"]
    name: Run linters with Bun ${{ matrix.bun }}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ matrix.bun }}

      - name: Install dependencies
        run: bun install

      - name: Run ESLint
        uses: wearerequired/lint-action@v2
        with:
          github_token: ${{ secrets.github_token }}
          # Enable linters
          eslint: true
